First project pull request
Kwamay/Hello_Microverse_Project pull request #1
Opened 2023-06-01 10:52 UTC by Kwamay

-[ ] Added html file
-[ ] Added css file 
-[ ] Added Readme file
-[ ] Added linters to project

2023-06-01 11:51 UTC, amon-cofie requested changes
Hi @Kwamay , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 💪 

<img src="https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights

🚀 You have a descriptive pull request summary
🚀 node_modules and test.md file are successfully ignored
🚀 You have good commit messages

## Required Changes ♻️

Your linter checks seem not to be running and I think the problem is the naming of the workflows directory. I think the directory should be ```.github/workflows``` but yours is named ```.github/workflow```. Please correct this by adding an 's' to workflow 👍 

![image](https://github.com/Kwamay/Hello_Microverse_Project/assets/107795045/a6d2b8b9-53b7-4262-9727-3bb964f09995)

![image](https://github.com/Kwamay/Hello_Microverse_Project/assets/107795045/59414fcb-72cd-4f9e-8d5d-13001366cdc5)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 11:51 UTC, amon-cofie commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Since you do not have a deployed version of the project, I think you can feel free to remove the live demo section from your readme

2023-06-01 11:51 UTC, amon-cofie commented on README.md
> +
Similar to the previous comment, you can feel free to remove these sections from the readme since they don't apply to this project. 👍

2023-06-01 11:51 UTC, amon-cofie commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Unfortunately, the link to your MIT license file seems to be broken but the fix is very easy. There is a ```NOTE``` at the bottom of the [Microverse readme template](https://github.com/microverseinc/readme-template) that contains instructions on how to add a license file to your project. I will also paste the note here so you can access easily: 

NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish.

2023-06-01 12:37 UTC, Kwamay reviewed
License added and readme modified

2023-06-01 15:11 UTC, Kwamay reviewed
added LICENSE to main anf first_br

2023-06-03 13:59 UTC, abdulhamiid approved these changes
# :green_circle:  Approved! :partying_face:
Hi @Kwamay 👋, 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 16:56 UTC, merged